<b>Joseph Logan<br>
Joseph_logan@Yahoo.com
<br>
<font size = 7><center>Sr. Data Analyst/BI assignment</center></font> </b>

<b>Importing packages and csv files.</b>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.mlab as mlab
import re
import csv

In [3]:
opioids = pd.read_csv('opioids.csv')
prescribers = pd.read_csv('prescriber-info.csv')

<b>Viewing raw data and statistics.</b>

In [4]:
prescribers.head()

,NPI,Gender,State,Credentials,Specialty,ABILIFY,ACETAMINOPHEN.CODEINE,ACYCLOVIR,ADVAIR.DISKUS,AGGRENOX,...,VERAPAMIL.ER,VESICARE,VOLTAREN,VYTORIN,WARFARIN.SODIUM,XARELTO,ZETIA,ZIPRASIDONE.HCL,ZOLPIDEM.TARTRATE,Opioid.Prescriber
0,1710982582,M,TX,DDS,Dentist,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1245278100,F,AL,MD,General Surgery,0,0,0,0,0,...,0,0,0,0,0,0,0,0,35,1
2,1427182161,F,NY,M.D.,General Practice,0,0,0,0,0,...,0,0,0,0,0,0,0,0,25,0
3,1669567541,M,AZ,MD,Internal Medicine,0,43,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1679650949,M,NV,M.D.,Hematology/Oncology,0,0,0,0,0,...,0,0,0,0,17,28,0,0,0,1

In [5]:
prescribers.describe()

,NPI,ABILIFY,ACETAMINOPHEN.CODEINE,ACYCLOVIR,ADVAIR.DISKUS,AGGRENOX,ALENDRONATE.SODIUM,ALLOPURINOL,ALPRAZOLAM,AMIODARONE.HCL,...,VERAPAMIL.ER,VESICARE,VOLTAREN,VYTORIN,WARFARIN.SODIUM,XARELTO,ZETIA,ZIPRASIDONE.HCL,ZOLPIDEM.TARTRATE,Opioid.Prescriber
count,2.500000e+04,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,...,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,1.498162e+09,3.157160,2.370400,1.05368,7.041000,0.708440,8.962840,9.305720,16.12812,2.394840,...,2.18804,2.238160,2.551600,0.806240,19.198040,3.348240,4.070880,1.119440,11.573120,0.587520
std,2.877233e+08,20.755819,11.631601,6.66110,25.898648,5.224049,36.520987,29.375476,69.35317,14.266314,...,10.08554,13.325884,23.327117,4.951929,86.501125,17.127556,18.467437,10.299475,39.136616,0.492291
min,1.003002e+09,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.245473e+09,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.497842e+09,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,1.740406e+09,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,1.992999e+09,770.000000,644.000000,356.00000,1105.000000,275.000000,2431.000000,790.000000,5716.00000,596.000000,...,528.00000,902.000000,1814.000000,143.000000,6029.000000,596.000000,772.000000,694.000000,2107.000000,1.000000

<b> Opiates are not defined in 'prescriber-info.csv'
    opioids.csv has different names often with extra “.” etc. 
    Using re.sub to only get columns in opioids.csv</b>

In [6]:
ops = list(re.sub(r'[-\s]','.',x) for x in opioids.values[:,0])
prescribed_ops = list(set(ops) & set(prescribers.columns))

for i,drug in enumerate(prescribed_ops):
    print (i+1,drug)

1 FENTANYL
2 ACETAMINOPHEN.CODEINE
3 HYDROCODONE.ACETAMINOPHEN
4 MORPHINE.SULFATE
5 METHADONE.HCL
6 OXYCONTIN
7 OXYCODONE.HCL
8 MORPHINE.SULFATE.ER
9 TRAMADOL.HCL
10 HYDROMORPHONE.HCL
11 OXYCODONE.ACETAMINOPHEN

<b>These 11 are opioids.</b>

<b> Problem 1: Find the specialty which prescribes opiates more than others. Present information by state.
   
   I will use the Column Opioid.Prescriber.</b>

In [7]:
stateCount_PrescribedOpiods = pd.DataFrame(prescribers.loc[prescribers['Opioid.Prescriber']>0])
df = pd.DataFrame(stateCount_PrescribedOpiods[['State','Specialty','Opioid.Prescriber']])

SpecGrp = df.groupby(['Specialty',])[['Opioid.Prescriber']].sum()
SpecGrpResult = SpecGrp.sort_values(by='Opioid.Prescriber', ascending=False)

<b>First, lets look at specialty.</b>

In [8]:
SpecGrpResult.head(5)

                     Opioid.Prescriber
Specialty
Family Practice                   2635
Internal Medicine                 2426
Nurse Practitioner                1350
Physician Assistant               1262
Dentist                           1058

<b>Next, I will group by specialty and state. I'll sort by the top opioid prescriber.</b>

In [9]:
Grp = df.groupby(['Specialty','State'])[['Opioid.Prescriber']].sum()
Result = Grp.sort_values(by='Opioid.Prescriber', ascending=False)
Result.head(20)

                           Opioid.Prescriber
Specialty           State
Family Practice     CA                   283
Internal Medicine   CA                   278
                    NY                   233
                    FL                   173
Family Practice     TX                   169
                    PA                   145
                    FL                   140
Internal Medicine   TX                   132
Physician Assistant CA                   123
Family Practice     OH                   117
                    MI                   112
Internal Medicine   PA                   109
                    IL                   109
Emergency Medicine  CA                   107
Family Practice     IL                   103
                    NY                   102
Dentist             TX                   101
Physician Assistant NY                   100
Internal Medicine   MA                    93
Dentist             CA                    91

<b> Problem 2: Find the most “popular” opiate. Present the distribution by states and specialties. 
    
   I'll use python and Excel to clean/organize the data and Tableau to display it.</b>

In [10]:
popOpiate = prescribers[['Specialty','State','METHADONE.HCL',
 'OXYCODONE.ACETAMINOPHEN',
 'HYDROCODONE.ACETAMINOPHEN',
 'ACETAMINOPHEN.CODEINE',
 'FENTANYL',
 'TRAMADOL.HCL',
 'MORPHINE.SULFATE.ER',
 'OXYCODONE.HCL',
 'MORPHINE.SULFATE',
 'OXYCONTIN',
 'HYDROMORPHONE.HCL']]
psum = popOpiate.sum(numeric_only=True)
psum = psum.sort_values(ascending=False)
psum
popOpiate.to_csv("popular.csv")

HYDROCODONE.ACETAMINOPHEN    958082
TRAMADOL.HCL                 406693
OXYCODONE.ACETAMINOPHEN      242914
OXYCODONE.HCL                172411
MORPHINE.SULFATE.ER           88305
FENTANYL                      85443
ACETAMINOPHEN.CODEINE         59260
OXYCONTIN                     49872
METHADONE.HCL                 35818
HYDROMORPHONE.HCL             23177
MORPHINE.SULFATE              20738
dtype: int64

<b>It looks like HYDROCODONE.ACETAMINOPHEN is the most popular by a lot!</b>

In [25]:
%%HTML

<script type='text/javascript' src='https://us-east-1.online.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1600px; height: 704px;'><object class='tableauViz' width='1600' height='704' style='display:none;'><param name='host_url' value='https%3A%2F%2Fus-east-1.online.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='&#47;t&#47;joeylogan' /><param name='name' value='opioids&#47;PrescriptionsByState' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='showAppBanner' value='false' /><param name='filter' value='iframeSizedToWindow=true' /></object></div>

TEST

<iframe src="https://us-east-1.online.tableau.com/t/joeylogan/views/opioids/PrescriptionsByState?:showVizHome=no&:embed=true" width="90%" height="500"></iframe>

In [ ]:
%%HTML

<script type='text/javascript' src='https://us-east-1.online.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1600px; height: 704px;'><object class='tableauViz' width='1600' height='704' style='display:none;'><param name='host_url' value='https%3A%2F%2Fus-east-1.online.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='&#47;t&#47;joeylogan' /><param name='name' value='opioids&#47;ByStateAndSpecialty' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='showAppBanner' value='false' /><param name='filter' value='iframeSizedToWindow=true' /></object></div>

<b> Problem 3: Find the most “popular” drug that is not opiate itself, but which is prescribed with most opiates.</b>

In [18]:
nonops = list(set(prescribers.columns)-set(ops))
nonopsdf = list(set(nonops)& set (prescribers.columns))
nonopsdf.append('Opioid.Prescriber')

nonpopOpiate = prescribers[nonopsdf]

nonpopOpiate.to_csv("test.csv")

drugsnotop = pd.read_csv('drugsnotops.csv')

In [20]:
dsum = drugsnotop.sum(numeric_only=True)
dsum = dsum.sort_values(ascending=False)
dsum.head(10)

LEVOTHYROXINE.SODIUM    1080045
LISINOPRIL              1043966
AMLODIPINE.BESYLATE      995064
SIMVASTATIN              953626
OMEPRAZOLE               920392
ATORVASTATIN.CALCIUM     853367
FUROSEMIDE               736799
METFORMIN.HCL            677826
GABAPENTIN               609687
METOPROLOL.TARTRATE      561915
dtype: int64

<b> LEVOTHYROXINE.SODIUM Is the most popular drug that is not opiate itself butt is prescribed with opiates.</b>